# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'come-in-pillow-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  # Pods for come-in-pillow-swift

  target 'come-in-pillow-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'come-in-pillow-swiftUITests' do
    # Pods for testing
  end

end
